<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>BP Gaming</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="theme-color" content="#282828" />

        <link href="/style/site.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave+Display" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    </head>
    <body>
        <h1><span>BP</span>GAMING</h1>
        <h2>Coming Soon</h2>
    </body>
</html>
